# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3c99f61650c6648d175a3a88e0c85b5d4b376d6d8ecf3da2d5d57a635bf9e6ef9d410a93dbc6ae941001cae9626f69db47e1348e90123976dd8765df09a1c5aa

test:
  secret_key_base: 4e00d493158fa390b93b91d2eeb58123eece166c4eaf0a8288c7cd5e85b4073dec46f2fb8b15c7ef8894718bfd0a168f04f577058ee59cc9bec92fc37cdb3c89

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
